# Copyright © Idiap Research Institute <contact@idiap.ch>
#
# SPDX-License-Identifier: BSD-3-Clause

# pre-commit is a tool to perform a predefined set of tasks manually and/or
# automatically before git commits are made.
#
# Config reference: https://pre-commit.com/#pre-commit-configyaml---top-level
#
# Common tasks
#
# - Run on all files:   pre-commit run --all-files
# - Register git hooks: pre-commit install --install-hooks
#
repos:
  # Autoformat: Python code, syntax patterns are modernized
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.16.0
    hooks:
      - id: pyupgrade
        args:
          - --py38-plus

  # Autoformat: Python code
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
        # args ref: https://github.com/PyCQA/autoflake#advanced-usage
        args:
          - --in-place

  # Autoformat: Python code
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort

  # Autoformat: Python code
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black

  # Autoformat: markdown, yaml
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier

  # Misc...
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    # ref: https://github.com/pre-commit/pre-commit-hooks#hooks-available
    hooks:
      - id: end-of-file-fixer
      - id: check-case-conflict
      - id: check-executables-have-shebangs

  # Lint: Python code
  - repo: https://github.com/pycqa/flake8
    rev: "7.1.0"
    hooks:
      - id: flake8

  # Lint: ensure code does not contain vulnerable patterns
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.9
    hooks:
      - id: bandit
        args: [-c, .bandit]

  # Ensure project content is properly license and copyrighted
  - repo: https://github.com/fsfe/reuse-tool
    rev: v4.0.3
    hooks:
      - id: reuse

  # Follow conventional commits standard
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: "v3.3.0"
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []

# pre-commit.ci config reference: https://pre-commit.ci/#configuration
ci:
  autoupdate_schedule: monthly
